[project]
name = "protonge-fetcher"
version = "0.1.0"
description = "Grab the latest Proton-GE release from GitHub and keep 'compatibility.d' up-to-date"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.2",
    "pytest-mock>=3.15.1",
    "slipcover>=1.0.17",
]
